### ISSUE TITLE
recursive browsing mode 

### ISSUE THREAD

**Issue by Fischmuetze** [netdcy/FlowVision#10]
Found this in the release notes 
"Introduced recursive browsing mode (displays all images in a folder and its subdirectories). "
Thank you! Works quite well so far 
... would be nice to have a quickly visible indicator that the recursive mode is activated e.g. as toolbar button ...
... also there are small inconsistencies between the View Menu and the View  Button in the Toolbar 
The Info entry in the menu of the view button confuses users, as one would expect ‘Info’ to display additional file information rather than a dialogue that provides an explanation of a function

**Comment by netdcy** [comment]
1. Because I don't use the recursive mode often, regarding its logic, do you think it requires manually clicking each time after entering a folder to activate it, or should it remain active until it's manually turned off? If it's the former, then no indicator is needed.
2. I have to do this because I'm always asked what these modes mean. Maybe I should use a different word instead of "Info"?

**Comment by Fischmuetze** [comment]
> Because I don't use the recursive mode often, regarding its logic, do you think it requires manually clicking each time after entering a folder to activate it, or should it remain active until it's manually turned off?  If it's the former, then no indicator is needed.

Imho ist should be better to keep it persistent on until it switched off. Could be annoying to enable it each time ... 
In any case I would prefer an indicator ... in my opinion a toolbar button would be the best way - on the one site it indicates the current state, on the other hand it is offering the possibility for switching the function

> I have to do this because I'm always asked what these modes mean. Maybe I should use a different word instead of "Info"?

Not sure what would be the best - a tool tip is one of the common solution, a help file another one - dialog boxes as help tool is more or less unusually

**Comment by netdcy** [comment]
In v1.2.5, I added an icon to the toolbar to indicate whether recursive mode is enabled.
