### ISSUE TITLE
There's no apparent way to get out of single-image view

### ISSUE THREAD

**Issue by Stokestack** [netdcy/FlowVision#11]
There's no Back button or other on-screen control to allow the user to go back to the gallery (thumbnail) view after double-clicking to open a single image.

Pressing Escape (which wouldn't be a sufficient solution by itself anyway) quits the app... which is also unexpected.

**Comment by netdcy** [comment]
You can go back to the gallery (thumbnail) view by double click!

**Comment by Stokestack** [comment]
Thanks, but there's no way for the user to know that. This is not standard GUI behavior. When you enter a "detail" view of something, there is always a "back" button or a "close" button.

**Comment by netdcy** [comment]
When users are unable to exit, they tend to click the mouse randomly, and the first item in the right-click menu is "Close (Double-click)".

I observed that only about 2% of users experience this confusion, so I have decided not to make any changes for now.

Do you have a better suggestion regarding the prompt?

**Comment by netdcy** [comment]
Thank you for your suggestion, and apologize for the late reply.

Regarding double-click to close, I have already added a prompt when the program starts for the first time.

As for the Esc key to exit, it is mainly for a "boss key" function to allow quick exit in certain situations.

Regarding the other toolbar button issues, sorry I disagree with your opinion, so this part will not be changed for now.

**Comment by Stokestack** [comment]
No worries! Thanks for the reply. I don't think a one-time prompt at program launch will be remembered; it _might_ be remembered if you presented it the first time the user goes into single-image mode.

Since you mentioned Escape being the "boss key," I kind of like that idea and changed my mind on it. Maybe make that a configurable option?
