### ISSUE TITLE
记住排序方式

### ISSUE THREAD

**Issue by sogoo** [netdcy/FlowVision#15]
希望能记住上次选择的排序方式，而不用每次打开都需要重选。

**Comment by netdcy** [comment]
因为缩略图视图不像finder中列表视图那样，表头能清楚地显示当前的排序方式，我担心记住上次排序会让用户感觉不能清楚的掌握当前状态。
有三种选择：
1. 当前的逻辑：默认按文件名，改变后全局改变，不记忆
2. 按文件夹记忆
3. 全局改变记忆

**Comment by sogoo** [comment]
或者可以在设置里给个选项，需要记忆排序的才勾选。

**Comment by sogoo** [comment]
已更新，感谢。
