### ISSUE TITLE
Key commands locked to US/EN keyboard, unusable on Nordic keyboard

### ISSUE THREAD

**Issue by cybrgloom** [netdcy/FlowVision#16]
Hey neat app,

it seems like the app shortcuts are hardcoded to exact physical keys and not the semantic value of the key? I.e. it is not waiting for a "plus" sign to be typed, regardless of where that key is, it is waiting for that physical key to be hit. 

On Norwegian keyboard, the + and - keys are in different positions than English/US. (The Norwegian PLUS is actually where the English MINUS is. I know this because this problem has happened a thousand times before in apps that doesn't think beyond English keyboards.) In this app, hitting the Norwegian PLUS seems to trigger the English MINUS, the thumbnails go smaller, opposite of what is expected. Nothing happens when hitting MINUS. So I can only make smaller thumbnails, and counterintuitively only do it when hitting PLUS.

**Comment by netdcy** [comment]
Thank you for your feedback. That is interesting. I have changed it to determine the key based on semantics and re-uploaded version 1.2.4. Please check if it is effective?

**Comment by cybrgloom** [comment]
Hi, that works! Just downloaded 1.2.4 now and testet, and now the Zoom /
Thumbnail size keys (plus, minus) work as expected on Norwegian keyboard!

Thanks! Now I can use the app!! 😍
