### ISSUE TITLE
双指滑动图片时会多滑动一张

### ISSUE THREAD

**Issue by faimin** [netdcy/FlowVision#17]
举个例子：当前是图片`A`，在我双指滑动时是想查看下一张图片`B`，但表现是滑动到`B`后又到了`C`，最终停在了`C`，与预期不符。

**Comment by netdcy** [comment]
这是触控板滚动具有惯性造成的。
当然可以检测当前是不是处在惯性滚动阶段，我在1.2.5改了下，屏蔽了惯性滚动要停下时产生的最后一次间隔0.5秒的那次滚动，感觉这样会比较符合直觉。
