### ISSUE TITLE
默认打开方式

### ISSUE THREAD

**Issue by kitawa1981** [netdcy/FlowVision#18]
现在：如果已经有打开一个图片或者预览，双击打开新的图片会覆盖当前标签页
希望：不改动已有的页面，打开新的图片时启用新的标签页
使用场景：收集资料需要同时打开很多标签页，不希望新打开的图片覆盖原有的

还有建议在侧边栏增加收藏夹

**Comment by netdcy** [comment]
已在1.2.5改变，现在从文件打开图像时会在新标签页打开。

侧边栏收藏夹好像有点麻烦，等有时间的话看看。
