### ISSUE TITLE
提几个建议，希望越做越好

### ISSUE THREAD

**Issue by kitawa1981** [netdcy/FlowVision#2]
1.希望侧边栏树形文件夹不要显示隐藏文件夹
2.能像PictureView一样自定义快捷键
3.网格视图样式过丑，和其他样式格格不入
4.键盘快捷键放大缩小不够丝滑
5.esc键不要关闭app
6.希望通过点击顶部标题栏的路径来切换文件夹
7.自动隐藏顶部标题栏
8.删除图片可以不弹出确认
9.右键菜单图片旋转希望做成PictureView那样，并且加入左右旋转（镜像）
10.双图片浏览模式（可以参考EdgeView）

**Comment by netdcy** [comment]
1.希望侧边栏树形文件夹不要显示隐藏文件夹  
并没有吧，有显示隐藏文件选项，行为和finder一致
2.能像PictureView一样自定义快捷键 
因为最初开发是为了自用，所以不特别影响使用而又比较麻烦的功能，目前优先级要低一些
3.网格视图样式过丑，和其他样式格格不入  
这个确实，因为这个不像网页那样能简单实现阴影等效果还不影响性能，需要一定的工作量
4.键盘快捷键放大缩小不够丝滑 
之后会优化一下
5.esc键不要关闭app  
那么你想按esc键有什么行为呢
10.双图片浏览模式（可以参考EdgeView）
这个有点麻烦

6.希望通过点击顶部标题栏的路径来切换文件夹 
7.自动隐藏顶部标题栏  
8.删除图片可以不弹出确认  
9.右键菜单图片旋转希望做成PictureView那样，并且加入左右旋转（镜像）  
这些其实已在todolist中，还没有做

**Comment by kitawa1981** [comment]
感谢回复~
1.是外置硬盘会显示隐藏文件夹，内置倒是和Finder的一致。
5.esc不要任何生效也可以。这个还是应该归纳在自定义快捷键的范畴。

再提一个建议：希望缩略图模式下支持直接把图片拖进其他app里

**Comment by netdcy** [comment]
1. 感谢测试，这个应该是bug，下个版本会修复
2. 拖拽功能正在计划中

**Comment by postblue** [comment]
@netdcy 能否增加小众功能
1. 希望有个记忆功能，可以设置开关。比如我浏览A文件夹下007.jpg时退出了软件，下次打开时可以自动定位并打开007.jpg

**Comment by netdcy** [comment]
> @netdcy 能否增加小众功能
> 
> 1. 希望有个记忆功能，可以设置开关。比如我浏览A文件夹下007.jpg时退出了软件，下次打开时可以自动定位并打开007.jpg

这个太小众了，不适合添加吧

**Comment by postblue** [comment]
> > @netdcy能否重新创建小众功能
> > 
> > 1. 希望有记忆功能，可以设置开关。比如我浏览A文件夹下007.jpg时退出了软件，下次打开时可以自动定位并打开007.jpg
> 
> 这个公众号太小了，不适合添加吧

那这样可以吗？
1. 打开软件，自动定位到上次打开的文件夹。[这个已经实现]
2. 选中最后一次打开或者预览的图片(就是软件右侧第一行是有最后一次打开的图片)。
预期结果：
打开软件，自动定位到上次打开的文件夹，自动选中最后一次访问的图片。

这样应该就不是太小众了吧？

**Comment by netdcy** [comment]
因为这个软件为了优化目录中存在大量文件的情况，所以载入逻辑比较复杂，加个这个会很麻烦，所以暂时不计划实现。
如果还有其他问题，请另外提issue，谢谢！
