### ISSUE TITLE
"Open with" doesn't open all selected images

### ISSUE THREAD

**Issue by Stokestack** [netdcy/FlowVision#24]
If you select multiple images and then right-click and do "Open with...", only the last image is opened.

**Comment by netdcy** [comment]
Yes, to open multiple files, we need to find the intersection of the opening methods. If there's time later, this will be implemented.

**Comment by netdcy** [comment]
This has been implemented in ver 1.2.6.

**Comment by Stokestack** [comment]
Another usability win, thanks!
