### ISSUE TITLE
Shift-click doesn't select a range

### ISSUE THREAD

**Issue by Stokestack** [netdcy/FlowVision#25]
If you select a thumbnail and then Shift-click on another one that is several images away, the two thumbnails _and everything between them_ should be selected.

Currently, Shift-click only adds the single image to the selection. This is what Command-click (Mac) or Ctrl-click (Windows) does.

Good job on the application! It's my only go-to image browser now.

**Comment by netdcy** [comment]
Thank you!
This has been implemented in ver 1.2.6 (But the behavior is slightly different for ease of implementation).

**Comment by Stokestack** [comment]
Nice! Very useful addition, thanks.
