### ISSUE TITLE
打开大量图片时缩略图不显示

### ISSUE THREAD

**Issue by ma3252788** [netdcy/FlowVision#26]
打开了一个有二十多万张图片的文件夹，发现缩略图加载不出来了。。
<img width="1434" alt="image" src="https://github.com/user-attachments/assets/19cbfd26-4fa6-44e6-83a8-cf76ce3cad21">

**Comment by netdcy** [comment]
我看着没法显示的图片都是facebook开头的，这些训练用的图片是正常图像格式吗？单独复制到一个文件夹能显示吗？
