### ISSUE TITLE
界面样式建议：使用 macOS 用户定义的主题色

### ISSUE THREAD

**Issue by Rereyuop** [netdcy/FlowVision#30]
### 现状
<img width="778" alt="image" src="https://github.com/user-attachments/assets/706b94a3-95b9-45fb-ae42-99cfce66c01e">

现在的颜色一直是蓝色，如果能用系统设定的主题色，会更加统一，也更加个性化。

第三方 app 如 Qspace 也有这个能力。

### 参考
<img width="589" alt="image" src="https://github.com/user-attachments/assets/5923e116-13c7-4713-9d94-69fe83a53d5c">

**Comment by netdcy** [comment]
感谢反馈，你是修改了系统设置里的外观->“强调色”吗？
选中的项目的颜色将会在下个版本更改

**Comment by Rereyuop** [comment]
是的，是强调色（苹果表述）哈哈，谢谢！
