### ISSUE TITLE
Installable by Homebrew

### ISSUE THREAD

**Issue by Accademia** [netdcy/FlowVision#31]
I hope to install this software via Homebrew. You can refer to other implementations, such as https://github.com/viarotel-org/homebrew-escrcpy.

They achieved Homebrew installation by setting up their own repository. I hope you can do the same. Thank you very much!

**Comment by netdcy** [comment]
Hi, it's already implemented and mentioned in the readme.  
Additionally, due to the lack of an Apple certificate, it cannot be uploaded to the official Homebrew repository.
