### ISSUE TITLE
像访达一样支持快捷键前进、后退 cmd+【/】

### ISSUE THREAD

**Issue by Rereyuop** [netdcy/FlowVision#32]
目前只有A和D的跨越文件夹查看，回到上一级只能点树形图。

现在进入子级和返回上一级的快捷键是 W 和 D 吗？但是操作反馈感觉不太像。

建议可以加入和系统一样的前进、后退快捷键，比较符合习惯。

**Comment by netdcy** [comment]
设置里有说明，w是父目录，s是返回上一步。

cmd+【】可以作为前进后退，我稍后加上
cmd+上 用作跳到顶部了（chrome是cmd+上下），还是用w吧？
