### ISSUE TITLE
能不能加一个显示隐藏文件名的选项？

### ISSUE THREAD

**Issue by willianzjy0809** [netdcy/FlowVision#7]
首先这个软件做的非常到位，非常感谢开发。
我不知道有没有可能给软件加个显示隐藏文件名的功能？
这样显示缩略图，给缩略图截图效果可能会更好，谢谢。

![截屏2024-08-13 20 14 14 拷贝](https://github.com/user-attachments/assets/4ddae3f6-7b11-4243-a4ca-2c9e8f1f8a86)

**Comment by netdcy** [comment]
单纯隐藏文字倒是容易，只是下面那个框的高度，都是在可视化编辑器里设置的，动态改起来要麻烦一些😅或许以后会弄一个纯看图模式

**Comment by willianzjy0809** [comment]
如果可以这样就太好了，能截个图告诉我具体哪里改吗？
我想先改一版自己的，不用通过设置开启关闭的，谢谢！

**Comment by netdcy** [comment]
可以，请看no-image-name分支
[FlowVision.app.zip](https://github.com/user-attachments/files/16613253/FlowVision.app.zip)

**Comment by willianzjy0809** [comment]
你都帮我做了！太谢谢了，我找一下，等你有新版本了我自己可以编译，谢谢！学习啦！
