### ISSUE TITLE
访问NAS，局域网文件时候异常缓慢

### ISSUE THREAD

**Issue by willianzjy0809** [netdcy/FlowVision#8]
比起自带的预览，或者一些其他图片查看器，当访问nas上照片时候加载超级缓慢，不知道哪里需要改的？

<img width="1182" alt="Snipaste_2024-08-14_17-06-37" src="https://github.com/user-attachments/assets/7a26be37-73a3-4f98-964a-30f0f710e621">

**Comment by netdcy** [comment]
给你发邮件了，私信联系一下，看看环境有什么特点？

**Comment by netdcy** [comment]
已在1.2.4版本修复。

原因是以Linux文件系统为基础的Samba服务端，在进行很多读取操作时会导致文件的access time发生改变，产生文件系统的write和attrib事件，频繁触发刷新而造成卡顿。
