### ISSUE TITLE
New Tab Command Opens New Window Instead

### ISSUE THREAD

**Issue by cyclelou** [netdcy/FlowVision#9]
When I click New Tab, a new Window opens instead.

**Comment by netdcy** [comment]
Have you enabled the "Auto hide toolbar" option? Tabs cannot be used when it is enabled. Or in mac system settings, you chose to prefer not using tabs.

**Comment by Fischmuetze** [comment]
same here

**Comment by netdcy** [comment]
Have you checked this?
![SCR-20240820-nvcd](https://github.com/user-attachments/assets/2ab67a43-a0a5-4c61-838b-5dbdab0b4eb7)

**Comment by Fischmuetze** [comment]
yes but I never changed that setting so I guess it is always on my Macs in the default mode and the default mode seems to be "In Full Screen". Honestly I have no clue for what this setting affected ...   So all other apps that I use and supporting tabs reacting independently of this setting and open a tab if they offer a function to open some what in a new tab and open a new window if there is a function New window -> see e.g. the Mail App or still better one The Finder

**Comment by netdcy** [comment]
OK... I should add a setting option in app, and make "Always" the default value, in next version. I hadn't paid attention to this issue before.
